### ISSUE TITLE
Request for Woo help wrangling – week of Feb 10, 2020

### ISSUE THREAD

**Issue by lettergrade** [Automattic/happops#1]
@jesscga reached out to request 20 hours of time for help with the Woo queue backlog. @lettergrade is working it out. Updates below!

Also wanted to note here that past wrangling was documented here:

https://3.basecamp.com/3698594/buckets/12828225/messages/2305971871

**Comment by lettergrade** [comment]
**Requests**

Arun – on Atomic so I held off for now
Mark Senff – DMed
Gabriel Maldonado – AFK
Khyati Gala – DMed
Jaco Swanepoel – DMed
Damianne President – DMed
Davor A – AFK
Maciej P – AFK
Mike Straw – mostly AFK
Rafael – DMed

**Results so far**

Mark Senff – 10 hours

**Comment by lettergrade** [comment]
**Results so far**

Mark Senff – 10 hours (Weds/Thurs)
Jaco Swanepoel – 11 hours (Weds/Thurs)

@jesscga That should cover your request. All good?

**Comment by jesscga** [comment]
This is great, thank you!

Noting that @rantoncuadrado also added Damianne P. (6 hours) Feb 13th (Thurs)

**Comment by rantoncuadrado** [comment]
I added Jaco (5 hours) today. The queue in Wpcom was tiny and huge in Woo.
